//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist on your computer.
        /// </summary>
        internal static string FileNoExist {
            get {
                return ResourceManager.GetString("FileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.10.2 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
        /////@ sourceMappingURL=jquery-1.10.2.min.map
        ///*/
        ///(function(e,t){var n,r,i=typeof t,o=e.location,a=e.document,s=a.documentElement,l=e.jQuery,u=e.$,c={},p=[],f=&quot;1.10.2&quot;,d=p.concat,h=p.push,g=p.slice,m=p.indexOf,y=c.toString,v=c.hasOwnProperty,b=f.trim,x=function(e,t){return new x.fn.init(e,t,r)},w=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,T=/\S+/g,C=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,N=/^(?:\s*(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/,k=/^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_10_2_min {
            get {
                return ResourceManager.GetString("jquery_1_10_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* line 7, ../sass/lightbox.sass */
        ///body:after {
        ///  display: none;
        ///}
        ///
        ////* line 11, ../sass/lightbox.sass */
        ///.lightboxOverlay {
        ///  position: absolute;
        ///  top: 0;
        ///  left: 0;
        ///  z-index: 9999;
        ///  background-color: black;
        ///  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
        ///  opacity: 0.8;
        ///  display: none;
        ///}
        ///
        ////* line 20, ../sass/lightbox.sass */
        ///.lightbox {
        ///  position: absolute;
        ///  left: 0;
        ///  width: 100%;
        ///  z-index: 10000;
        ///  text-align: center;
        ///  line-height: 0;
        ///  font-weight: normal;
        ///}
        ////* line 28, ../sass/l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lightbox {
            get {
                return ResourceManager.GetString("lightbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(){var b,d,c;b=jQuery;c=(function(){function b(){this.fadeDuration=500;this.fitImagesInViewport=true;this.resizeDuration=700;this.showImageNumberLabel=true;this.wrapAround=false}b.prototype.albumLabel=function(b,c){return&quot;Image &quot;+b+&quot; of &quot;+c};return b})();d=(function(){function c(b){this.options=b;this.album=[];this.currentImageIndex=void 0;this.init()}c.prototype.init=function(){this.enable();return this.build()};c.prototype.enable=function(){var c=this;return b(&apos;body&apos;).on(&apos;click&apos;,&apos;a[rel^=lightbox] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lightbox_2_6_min {
            get {
                return ResourceManager.GetString("lightbox_2_6_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album displayed.
        /// </summary>
        internal static string NoAlbumDisplayed {
            get {
                return ResourceManager.GetString("NoAlbumDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album selected.
        /// </summary>
        internal static string NoAlbumSelected {
            get {
                return ResourceManager.GetString("NoAlbumSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    margin: 3rem 5rem;
        ///    text-align: center;
        ///}
        ///
        ///h1 {
        ///    text-align: center;
        ///    margin-bottom: 2rem;
        ///}
        ///
        ///.container {
        ///    width: 250px;
        ///    margin-top: .5rem;
        ///    display: inline-block;
        ///    vertical-align: middle;
        ///}
        ///
        ///.cadre {
        ///    max-width:200px;
        ///    max-height:200px;
        ///
        ///    border: 1rem solid #EEEEEE;
        ///
        ///    cursor: pointer;
        ///}.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
