//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18331
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        ///   Looks up a localized string similar to albums.xml.
        /// </summary>
        internal static string AlbumXmlFile {
            get {
                return ResourceManager.GetString("AlbumXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist on your computer.
        internal static string ExifAuthor {
            get {
                return ResourceManager.GetString("ExifAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bits per color.
        /// </summary>
        internal static string ExifBitsPerColor {
            get {
                return ResourceManager.GetString("ExifBitsPerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camera.
        /// </summary>
        internal static string ExifCamera {
            get {
                return ResourceManager.GetString("ExifCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copyright.
        /// </summary>
        internal static string ExifCopyright {
            get {
                return ResourceManager.GetString("ExifCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created.
        /// </summary>
        internal static string ExifCreated {
            get {
                return ResourceManager.GetString("ExifCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of shooting.
        /// </summary>
        internal static string ExifDateOfShooting {
            get {
                return ResourceManager.GetString("ExifDateOfShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exposition.
        /// </summary>
        internal static string ExifExposition {
            get {
                return ResourceManager.GetString("ExifExposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height.
        /// </summary>
        internal static string ExifHeight {
            get {
                return ResourceManager.GetString("ExifHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model.
        /// </summary>
        internal static string ExifModel {
            get {
                return ResourceManager.GetString("ExifModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software used.
        /// </summary>
        internal static string ExifSoftwareUsed {
            get {
                return ResourceManager.GetString("ExifSoftwareUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        internal static string ExifTitle {
            get {
                return ResourceManager.GetString("ExifTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exif version.
        /// </summary>
        internal static string ExifVersion {
            get {
                return ResourceManager.GetString("ExifVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width.
        /// </summary>
        internal static string ExifWidth {
            get {
                return ResourceManager.GetString("ExifWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File does not exist on your computer.
        /// </summary>
        internal static string FileNoExist {
            get {
                return ResourceManager.GetString("FileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à yyyy:MM:dd HH:mm:ss.
        /// </summary>
        internal static string formatDate {
            get {
                return ResourceManager.GetString("formatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /*! jQuery v1.10.2 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
        /////@ sourceMappingURL=jquery-1.10.2.min.map
        ///*/
        ///(function(e,t){var n,r,i=typeof t,o=e.location,a=e.document,s=a.documentElement,l=e.jQuery,u=e.$,c={},p=[],f=&quot;1.10.2&quot;,d=p.concat,h=p.push,g=p.slice,m=p.indexOf,y=c.toString,v=c.hasOwnProperty,b=f.trim,x=function(e,t){return new x.fn.init(e,t,r)},w=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,T=/\S+/g,C=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,N=/^(?:\s*(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/,k [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string jquery_1_10_2_min {
            get {
                return ResourceManager.GetString("jquery_1_10_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /* line 7, ../sass/lightbox.sass */
        ///body:after {
        ///  display: none;
        ///}
        ///
        ////* line 11, ../sass/lightbox.sass */
        ///.lightboxOverlay {
        ///  position: absolute;
        ///  top: 0;
        ///  left: 0;
        ///  z-index: 9999;
        ///  background-color: black;
        ///  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);
        ///  opacity: 0.8;
        ///  display: none;
        ///}
        ///
        ////* line 20, ../sass/lightbox.sass */
        ///.lightbox {
        ///  position: absolute;
        ///  left: 0;
        ///  width: 100%;
        ///  z-index: 10000;
        ///  text-align: center;
        ///  line-height: 0;
        ///  font-weight: normal [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string lightbox {
            get {
                return ResourceManager.GetString("lightbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (function(){var b,d,c;b=jQuery;c=(function(){function b(){this.fadeDuration=500;this.fitImagesInViewport=true;this.resizeDuration=700;this.showImageNumberLabel=true;this.wrapAround=false}b.prototype.albumLabel=function(b,c){return&quot;Image &quot;+b+&quot; of &quot;+c};return b})();d=(function(){function c(b){this.options=b;this.album=[];this.currentImageIndex=void 0;this.init()}c.prototype.init=function(){this.enable();return this.build()};c.prototype.enable=function(){var c=this;return b(&apos;body&apos;).on(&apos;click&apos;,&apos;a[rel^=lightbox] [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string lightbox_2_6_min {
            get {
                return ResourceManager.GetString("lightbox_2_6_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No album displayed.
        /// </summary>
        internal static string NoAlbumDisplayed {
            get {
                return ResourceManager.GetString("NoAlbumDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No album selected.
        /// </summary>
        internal static string NoAlbumSelected {
            get {
                return ResourceManager.GetString("NoAlbumSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename your picture.
        /// </summary>
        internal static string renameYourPicture {
            get {
                return ResourceManager.GetString("renameYourPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à body {
        ///    margin: 3rem 5rem;
        ///    text-align: center;
        ///}
        ///
        ///h1 {
        ///    text-align: center;
        ///    margin-bottom: 2rem;
        ///}
        ///
        ///.container {
        ///    width: 250px;
        ///    margin-top: .5rem;
        ///    display: inline-block;
        ///    vertical-align: middle;
        ///}
        ///
        ///.cadre {
        ///    max-width:200px;
        ///    max-height:200px;
        ///
        ///    border: 1rem solid #EEEEEE;
        ///
        ///    cursor: pointer;
        ///}.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tape the album&apos;s title.
        /// </summary>
        internal static string TapeTheAlbumsTitle {
            get {
                return ResourceManager.GetString("TapeTheAlbumsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
